name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the plugin
        run: npm run build

      - name: Prepare ZIP file
        id: zip
        run: |
          mkdir -p dist
          ZIP_FILE="${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          echo "Creating $ZIP_FILE ..."
          zip -r "dist/$ZIP_FILE" . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "src/*" \
            -x "*.zip"
          ls -l dist
          echo "ZIP_PATH=dist/$ZIP_FILE" >> $GITHUB_OUTPUT

      - name: Upload ZIP as artifact (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/*.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip.outputs.ZIP_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
